### ISSUE TITLE
Authentication / tokens for users to do any POST opperations

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/home-data-api#3]

**Comment by smitec** [comment]
I will add JSON Web Tokens (JWT) to the push endpoints. One thing we need to determine is how accounts should be made. Can anyone sign up?

**Comment by smitec** [comment]
The `develop` branch and the dev heroku instance (https://home-sales-data-api-dev.herokuapp.com/) now have this featue. There are some relevant docs here: http://data-skeptic-home-data-api.readthedocs.org/en/develop/api.html

**Comment by smitec** [comment]
Closing this now as we have users, and user types. We can open a new issue for the sign up process if need be.
