### ISSUE TITLE
Deduplication facilities

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/home-data-api#4]
As a data scientist / user of the API, I'd like to flag items as duplicates and provide both IDs for merging.

**Comment by smitec** [comment]
To keep this record up to date. As discussed in the meeting we will be adding the ability for users to push a flag object to the API. This object will reference two objects seen to be similar and a mode being one of: exact duplicate, merge duplicate. Others can be added later. Currently flagging and resolving will be limited to admin users until the different user levels are implemented.

**Comment by smitec** [comment]
Ironically this is probably a duplicate of #8 now. I'll close this as I closed that one.
