### ISSUE TITLE
Add in user permissions management

### ISSUE THREAD

**Issue by kylepolich** [data-skeptic/home-data-api#9]
Different tasks should be permitted by different user types.

`anon < user < flagger < admin github issue`

The API needs to support these sorts of access rights.  After that, deeper discussions about which endpoints need each status, and how status is awarded can then be discussed.

**Comment by smitec** [comment]
To keep things simple I'll be using Django's user groups for this (https://docs.djangoproject.com/en/1.9/topics/auth/default/#topic-authorization) We can see about programatically assigning groups later.

**Comment by smitec** [comment]
this has been pushed into develop as well as some initial tests
